-- Seed: office_sections backfill from hardcoded data in src/pages/about/OfficesHeadquarters.tsx
-- Source commit: 0ea7b78
-- Note: The old page referenced i18n keys (administrativeOffice, technicalBranch, etc.) that
-- did not have entries in src/constants/Language.ts. Reasonable English titles inferred
-- from the key names; Marathi reuses the same words where no translation existed.

INSERT INTO office_sections (slug, title_en, title_mr, incharge_en, incharge_mr, description_en, description_mr, display_order)
VALUES
  ('administrative_office', 'Administrative Office', 'प्रशासकीय कार्यालय', 'Office Superintendent', 'कार्यालय अधीक्षक', 'Handles RTI, yearly administrative reports, budget inspection, BMI quarters, bill payment orders, welfare/income tax/GST, accounts and pension, MAT cases, enquiries, gradation, promotions/transfers, service sheets, vacancy statements, classification exams, recruitment and procurement of spares.', 'माहिती अधिकार, वार्षिक प्रशासकीय अहवाल, अंदाजपत्रक तपासणी, बीएमआय क्वार्टर, देयक भुगतान आदेश, कल्याण/आयकर/जीएसटी, हिशेब आणि निवृत्तीवेतन, MAT प्रकरणे, चौकशी, सेवाज्येष्ठता, पदोन्नती/बदली, सेवा पुस्तके, रिक्त पदे विवरण, वर्गीकरण परीक्षा, भरती आणि सुटे भाग खरेदी हाताळते.', 1),
  ('technical_branch', 'Technical Branch', 'तांत्रिक शाखा', 'DySP (Admin)', 'उपपोलीस अधीक्षक (प्रशासन)', 'Supervises daily work across admin branches, technical branches, bandobast branch, planning branch, Home PI, welfare branch and SSS branch.', 'प्रशासकीय शाखा, तांत्रिक शाखा, बंदोबस्त शाखा, नियोजन शाखा, गृह पीआय, कल्याण शाखा आणि एसएसएस शाखेच्या दैनंदिन कामाचे पर्यवेक्षण करते.', 2),
  ('development_section', 'Development Section', 'विकास विभाग', NULL, NULL, 'Covers the computer section, radio communication, line communication, electrical section, installation branch and store section.', 'संगणक विभाग, रेडिओ संदेशवहन, लाईन संदेशवहन, विद्युत विभाग, स्थापना शाखा आणि भांडार विभागाचा समावेश आहे.', 3),
  ('vsat_section', 'V-SAT Section', 'व्ही-सॅट विभाग', 'DySP', 'उपपोलीस अधीक्षक', 'Monitors POLNET stations, guides POLNET units, ensures smooth POLNET operation and prepares specifications for POLNET/CCTV.', 'POLNET स्थानके निरीक्षण करते, POLNET युनिट्सना मार्गदर्शन देते, POLNET चे सुरळीत संचालन सुनिश्चित करते आणि POLNET/CCTV साठी विशेष नियमावली तयार करते.', 4),
  ('store_sections', 'Store Sections', 'भांडार विभाग', NULL, NULL, 'Comprises Store Section I, Store Section II and Store Section III.', 'भांडार विभाग I, भांडार विभाग II आणि भांडार विभाग III यांचा समावेश आहे.', 5),
  ('committee_section', 'Committee Section', 'समिती विभाग', NULL, NULL, 'Performs equipment checks and prepares test receipt reports.', 'उपकरणे तपासणी आणि चाचणी प्राप्ती अहवाल तयार करण्याचे काम करते.', 6),
  ('test_cell', 'Test Cell', 'चाचणी कक्ष', NULL, NULL, 'Testing of wireless equipment and maintenance of central store.', 'वायरलेस उपकरणांची चाचणी आणि मध्यवर्ती भांडाराची देखभाल.', 7),
  ('central_store_admin', 'Central Store Admin Section', 'मध्यवर्ती भांडार प्रशासकीय विभाग', NULL, NULL, 'Maintains inward/outward entries, record keeping and assists the store sections.', 'आवक/जावक नोंदी, अभिलेख व्यवस्थापन सांभाळते आणि भांडार विभागांना सहाय्य करते.', 8),
  ('cipher_branch', 'Cipher Branch', 'सायफर शाखा', 'DySP (Cipher)', 'उपपोलीस अधीक्षक (सायफर)', 'Custodian of cipher material; arranges couriers, coordinates crypto centers, runs cipher courses, maintains cipher docs, loads cipher programs and inspects crypto centers.', 'सायफर साहित्याचे रक्षक; कुरियर व्यवस्थापित करते, क्रिप्टो केंद्रांशी समन्वय साधते, सायफर अभ्यासक्रम चालवते, सायफर दस्तऐवज सांभाळते, सायफर प्रोग्राम लोड करते आणि क्रिप्टो केंद्रांची तपासणी करते.', 9),
  ('license_branch', 'License Branch', 'परवाना शाखा', 'DySP (License)', 'उपपोलीस अधीक्षक (परवाना)', 'Applies for radio licenses, pays spectrum charges, applies for frequencies, distributes network letters, handles traffic returns and prepares call signs.', 'रेडिओ परवान्यांसाठी अर्ज करते, स्पेक्ट्रम शुल्क भरते, फ्रीक्वेन्सीसाठी अर्ज करते, नेटवर्क पत्रांचे वितरण करते, ट्रॅफिक रिटर्न्स हाताळते आणि कॉल-साइन तयार करते.', 10),
  ('traffic_branch', 'Traffic Branch', 'ट्रॅफिक शाखा', 'DySP (Traffic)', 'उपपोलीस अधीक्षक (ट्रॅफिक)', 'Inspects POLNET stations, prepares call signs, conducts IT exams, supervises traffic cases and scrutinises security breaches.', 'POLNET स्थानके तपासते, कॉल-साइन तयार करते, IT परीक्षा घेते, ट्रॅफिक प्रकरणांचे पर्यवेक्षण करते आणि सुरक्षाभंगाची छाननी करते.', 11)
ON CONFLICT (slug) DO NOTHING;
