-- Seed: ranks backfill from hardcoded data in src/pages/about/Ranks.tsx
-- Source commit: 0ea7b78
-- Source for EN/MR: src/constants/Language.ts (ranks.rank1..rank18)

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM ranks) THEN
    INSERT INTO ranks (rank_en, rank_mr, description_en, description_mr, display_order) VALUES
      ('Addl. DGP & Director Police Communication, Information Technology & Transportation, M.S. Pune',
       'अपर पोलीस महासंचालक पोलीस दळणवळण व माहिती तंत्रज्ञान विभाग, महाराष्ट्र राज्य, पुणे',
       'Leads the entire department, sets strategic direction, ensures coordination across all units, and oversees communication, IT, and transportation functions statewide.',
       'संपूर्ण विभागाचे नेतृत्व करतो, धोरणात्मक दिशा निश्चित करतो, सर्व युनिटमध्ये समन्वय सुनिश्चित करतो आणि राज्यव्यापी संप्रेषण, आयटी आणि वाहतूक कार्ये देखरेख करतो.',
       1),
      ('Deputy Inspector General of Police Communication & Information Technology, M.S. Pune',
       'उप पोलीस महानिरीक्षक पोलीस दळणवळण व माहिती तंत्रज्ञान विभाग, महाराष्ट्र राज्य, पुणे',
       'Assists the Director in managing statewide operations, supervises technical teams, and ensures adherence to policies and standards.',
       'राज्यव्यापी कार्यप्रदर्शन व्यवस्थापित करण्यासाठी संचालकांची मदत करतो, तांत्रिक संघांचे पर्यवेक्षण करतो आणि धोरणे आणि मानकांचे पालन सुनिश्चित करतो.',
       2),
      ('Additional Commissioner of Police Communication & Information Technology, M.S. Mumbai',
       'अतिरिक्त पोलीस आयुक्त पोलीस दळणवळण व माहिती तंत्रज्ञान विभाग, महाराष्ट्र राज्य, मुंबई',
       'Leads Mumbai operations, manages critical IT infrastructure, ensures secure communications, and coordinates with local law enforcement units.',
       'मुंबई ऑपरेशन्सचे नेतृत्व करतो, गंभीर आयटी इन्फ्रास्ट्रक्चरचे व्यवस्थापन करतो, सुरक्षित संप्रेषण सुनिश्चित करतो आणि स्थानिक कायदा अंमलबजावणी युनिट्ससह समन्वय साधतो.',
       3),
      ('Supdt. Of Police Communication & Information Technology',
       'पोलीस अधीक्षक पोलीस दळणवळण व माहिती तंत्रज्ञान विभाग',
       'Supervises field units, monitors wireless systems, coordinates departmental activities, and ensures smooth day-to-day operations.',
       'फील्ड युनिट्सचे पर्यवेक्षण करतो, वायरलेस सिस्टीम मॉनिटर करतो, विभागीय क्रियाकलापांचे समन्वयन करतो आणि दैनंदिन कार्यसंचालन सुरळीतपणे सुनिश्चित करतो.',
       4),
      ('Deputy Commissioner of Police Communication & Information Technology',
       'उप पोलीस आयुक्त पोलीस दळणवळण व माहिती तंत्रज्ञान विभाग',
       'Oversees technical teams, manages operations, and provides guidance for implementing IT and communication strategies.',
       'तांत्रिक संघांचे पर्यवेक्षण करतो, ऑपरेशन्सचे व्यवस्थापन करतो आणि आयटी आणि संप्रेषण धोरणांच्या अंमलबजावणीसाठी मार्गदर्शन प्रदान करतो.',
       5),
      ('Deputy Supdt. Of Police /Asst. Commissioner of Police',
       'उप पोलीस अधीक्षक /सहाय्यक पोलीस आयुक्त',
       'Handles daily technical operations, staff assignments, troubleshooting, and ensures compliance with departmental protocols.',
       'दैनंदिन तांत्रिक कार्यसंचालन, कर्मचाऱ्यांची नियुक्ती, समस्या निवारण हाताळतो आणि विभागीय प्रोटोकॉलचे पालन सुनिश्चित करतो.',
       6),
      ('Police Inspector (PI)',
       'पोलीस निरीक्षक (PI)',
       'Supervises teams, monitors field communications, enforces regulations, and reports technical issues to senior officers.',
       'संघांचे पर्यवेक्षण करतो, फील्ड संप्रेषण मॉनिटर करतो, नियमांची अंमलबजावणी करतो आणि वरिष्ठ अधिकाऱ्यांना तांत्रिक समस्यांवर अहवाल देतो.',
       7),
      ('Police Sub-Inspector (PSI)',
       'पोलीस उपनिरीक्षक (PSI)',
       'Maintains wireless networks, supports investigations, and ensures effective communication within the unit.',
       'वायरलेस नेटवर्क्सचे देखभाल करतो, तपास करण्यासाठी समर्थन देते आणि युनिटमधील प्रभावी संप्रेषण सुनिश्चित करतो.',
       8),
      ('ASI (Senior Technical Officer)',
       'ASI (वरिष्ठ तांत्रिक अधिकारी)',
       'Leads technical projects, audits systems, trains junior staff, and ensures technical excellence across operations.',
       'तांत्रिक प्रकल्पांचे नेतृत्व करतो, सिस्टम ऑडिट करतो, कनिष्ठ कर्मचाऱ्यांना प्रशिक्षण देतो आणि ऑपरेशन्समध्ये तांत्रिक उत्कृष्टता सुनिश्चित करतो.',
       9),
      ('HC (Technical Officer)',
       'HC (तांत्रिक अधिकारी)',
       'Operates and maintains technical equipment, supports wireless and IT operations, and ensures continuous service.',
       'तांत्रिक उपकरणे चालवतो आणि देखभाल करतो, वायरलेस आणि आयटी ऑपरेशन्ससाठी समर्थन देते आणि सतत सेवा सुनिश्चित करतो.',
       10),
      ('ASI (Senior Technical Assistant)',
       'ASI (वरिष्ठ तांत्रिक सहाय्यक)',
       'Assists senior officers in technical tasks, system maintenance, and coordinates with field units.',
       'तांत्रिक कार्यांमध्ये वरिष्ठ अधिकाऱ्यांना मदत करतो, सिस्टम देखभाल आणि फील्ड युनिट्ससह समन्वय साधतो.',
       11),
      ('HC (Technical Assistant Grade II)',
       'HC (तांत्रिक सहाय्यक ग्रेड II)',
       'Handles administrative support, technical documentation, and assists in communication tasks.',
       'प्रशासकीय समर्थन, तांत्रिक दस्तऐवजीकरण हाताळतो आणि संप्रेषण कार्यांमध्ये सहाय्य करतो.',
       12),
      ('PN (Technical Assistant Grade I)',
       'PN (तांत्रिक सहाय्यक ग्रेड I)',
       'Performs day-to-day technical assistance, monitors equipment, and supports operations.',
       'दैनंदिन तांत्रिक सहाय्यक कार्य करतो, उपकरणे मॉनिटर करतो आणि ऑपरेशन्ससाठी समर्थन देते.',
       13),
      ('PC (Technical Assistant)',
       'PC (तांत्रिक सहाय्यक)',
       'Supports operations under supervision, assists in communication tasks, and maintains records.',
       'पर्यवेक्षणाखाली ऑपरेशन्ससाठी समर्थन देते, संप्रेषण कार्यांमध्ये सहाय्य करते आणि नोंदी राखते.',
       14),
      ('ASI (Driver)',
       'ASI (चालक)',
       'Provides transportation for high-ranking officers and supports operational logistics.',
       'उच्चपदस्थ अधिकाऱ्यांसाठी वाहतूक सेवा पुरवते आणि ऑपरेशनल लॉजिस्टिक्ससाठी समर्थन देते.',
       15),
      ('HC (Driver)',
       'HC (चालक)',
       'Ensures reliable transport for staff and equipment, assists in logistical planning.',
       'कर्मचाऱ्यांसाठी आणि उपकरणांसाठी विश्वासार्ह वाहतूक सुनिश्चित करते आणि लॉजिस्टिक नियोजनात मदत करते.',
       16),
      ('PN (Driver)',
       'PN (चालक)',
       'Supports vehicle operations and transportation coordination within the department.',
       'वाहन ऑपरेशन्स आणि विभागातील वाहतूक समन्वयासाठी समर्थन देते.',
       17),
      ('PC (Driver)',
       'PC (चालक)',
       'Handles routine driving duties, transport coordination, and ensures timely mobility of personnel.',
       'नियमित चालकीची कर्तव्ये हाताळते, वाहतूक समन्वय आणि कर्मचाऱ्यांची वेळेवर गतिशीलता सुनिश्चित करते.',
       18);
  END IF;
END $$;
